name: UI Tests

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    steps:
      # inspired by https://mathio28.medium.com/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-d5fbe4443692
      # to fix the issue with the runner running out of space
      - name: Aggressive cleanup
        run: |
          # Remove Java (JDKs)
          rm -rf /usr/lib/jvm
      
          # Remove .NET SDKs
          rm -rf /usr/share/dotnet
      
          # Remove Swift toolchain
          rm -rf /usr/share/swift
      
          # Remove Haskell (GHC)
          rm -rf /usr/local/.ghcup
      
          # Remove Julia
          rm -rf /usr/local/julia*
      
          # Remove Android SDKs
          rm -rf /usr/local/lib/android
      
          # Remove Microsoft/Edge and Google Chrome builds
          rm -rf /opt/microsoft /opt/google
      
          # Remove Azure CLI
          rm -rf /opt/az
      
          # Remove PowerShell
          rm -rf /usr/local/share/powershell
      
          # Remove CodeQL and other toolcaches
          rm -rf /opt/hostedtoolcache
      
          df -h
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run tests
        working-directory: apps/docs
        run: pnpm run test-storybook
